name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-app-name .
        docker push your-dockerhub-username/your-app-name

    # Step 4: SSH into EC2 and deploy the container
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker pull your-dockerhub-username/your-app-name
          sudo docker stop your-app || true
          sudo docker rm your-app || true
          sudo docker run -d --name your-app -p 80:80 your-dockerhub-username/your-app-name
